#!/usr/bin/env python3
# Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

# Copyright 2024 ROKCT INTELLIGENCE (PTY) LTD
"""Generate the SDK -> consuming-app-shells reverse index.

An app shell is a repository whose ROOT composer.json declares an `sdks`
list (the composed-shell contract, see SDK_ECOSYSTEM.md "App composition").
Each entry names an SDK and the source repository it is composed from. This
tool inverts that relationship across a multi-repo workspace so that anyone
changing an SDK can see every shell that composes it:

  python3 tools/gen_sdk_consumers.py

1. scans every sibling directory of this protocol checkout (override with
   --workspace DIR) for a root composer.json containing an `sdks` list,
2. records, per enabled SDK entry, its source repo (owner/repo from the
   entry's `git` URL) and the shell repos that compose it, and
3. writes both outputs at the repo root: sdk_consumers.json (machine
   readable, consumed by shared-workflows/scripts/sdk_validator.py) and
   SDK_CONSUMERS.md (the human-readable table).

It also refreshes the "Existing SDKs" census table in SDK_ECOSYSTEM.md:
every sibling repo that is not a shell but has top-level directories with
dart/manifest.json or frappe/manifest.json is an SDK monorepo, and each
such directory is one SDK row (dart/frappe half = its manifest.json
exists; nextjs half = nextjs/ has content beyond a .gitignore
placeholder). Only the block between the
`<!-- @generated-sdk-census-start -->` / `-end` markers is rewritten;
everything outside the markers is untouched.

Output is deterministic: sorted keys, LF line endings, trailing newline, no
timestamps — regenerating against an unchanged workspace produces zero diff.
Entries with `"enabled": false` are not composed into the shell and are
therefore not indexed. `paas_pos` is not indexed (retired: pos merged into
manager, there is no pos composer profile).
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
import urllib.error
import urllib.request

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_NAME = "sdk_consumers.json"
MARKDOWN_NAME = "SDK_CONSUMERS.md"
ECOSYSTEM_NAME = "SDK_ECOSYSTEM.md"

# Shell repos deliberately left out of the index. One-line note only.
EXCLUDED_SHELLS = {"paas_pos"}  # retired shell (pos merged into manager)

# "Existing SDKs" census block markers in SDK_ECOSYSTEM.md. Only the text
# between them is generated; the surrounding prose is hand-maintained.
CENSUS_START = "<!-- @generated-sdk-census-start -->"
CENSUS_END = "<!-- @generated-sdk-census-end -->"

# Doc order of the census table's repos (matches SDK_ECOSYSTEM.md's "SDK
# repo layout" narrative); repos not listed here sort after, by name.
CENSUS_REPO_ORDER = [
    "core",
    "Users",
    "agent",
    "commerce",
    "pay",
    "zones",
    "productivity",
    "hardware",
    "corporate",
    "forex",
    "designer",
]

MARKDOWN_HEADER = """# SDK consumers

Reverse index: for every SDK, the app shells that compose it. An app shell
is a repo whose root `composer.json` declares an `sdks` list (see
SDK_ECOSYSTEM.md, "App composition"); this table inverts those lists so a
change to an SDK can be checked against every shell that ships it — a
breaking SDK change must land together with fixes for all of its consumers
(backward-compatibility invariant, SDK_ECOSYSTEM.md).

Each row also carries the SDK's Next.js half, when it has one: its path in
the source repo, the `version` of `<sdk>/nextjs/manifest.json`, and its
pin — the SHA-256 of `<sdk>/nextjs/install.py` (CRLF folded to LF, the
digest a composer template's `sha256` carries and the composer's
unpinned-installer gate verifies). `nextjs_compose_example.json` at the
repo root, the composition RokctAI/factory seeds new Next.js shells from,
is generated from these columns alone (`tools/gen_nextjs_compose_example.py`):
the consumers file (path, version, pin) and the compose example change
together, in the same commit. An SDK with a Next.js half but no consumer
yet is listed too, with no shells.

Generated by `tools/gen_sdk_consumers.py` from a multi-repo workspace
checkout — do not edit by hand. Regenerate with:

```sh
python3 tools/gen_sdk_consumers.py
python3 tools/gen_nextjs_compose_example.py
```

Disabled entries (`"enabled": false`) are not composed and not indexed.
`paas_pos` is not indexed (pos merged into manager; there is no pos
composer profile). This index auto-refreshes weekly via the
`sdk-consumers-refresh.yml` workflow (Mondays 03:00 UTC).

| SDK | Source repo | Next.js path | Version | Pin (install.py sha256) | Consuming shells |
|---|---|---|---|---|---|
"""


def shell_repo_name(shell_dir):
    """The shell's repo name — from its git origin URL, else the dir name.

    Every shell's composer.json carries the same manifest name
    ("rokctapp_composer"), so the repository identity comes from the clone
    itself. The directory name is the fallback for non-git checkouts.
    """
    result = subprocess.run(
        ["git", "-C", shell_dir, "config", "--get", "remote.origin.url"],
        capture_output=True,
        text=True,
        check=False,
    )
    url = result.stdout.strip()
    if result.returncode == 0 and url:
        return url.rstrip("/").removesuffix(".git").rsplit("/", 1)[-1]
    return os.path.basename(os.path.normpath(shell_dir))


def source_repo(entry):
    """owner/repo from an sdks[] entry's `git` URL (e.g. RokctAI/core)."""
    url = (entry.get("git") or "").rstrip("/").removesuffix(".git")
    parts = url.split("/")
    if len(parts) >= 2 and parts[-2] and parts[-1]:
        return f"{parts[-2]}/{parts[-1]}"
    return ""


def load_shell_sdks(shell_dir):
    """The parsed `sdks` list of shell_dir's root composer.json, or None."""
    composer_path = os.path.join(shell_dir, "composer.json")
    if not os.path.isfile(composer_path):
        return None
    try:
        with open(composer_path, "r", encoding="utf-8-sig") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return None
    sdks = data.get("sdks")
    if not isinstance(sdks, list):
        return None
    return sdks


def scan_workspace(workspace):
    """Map sdk name -> {"repo": owner/repo, "consumers": [shell, ...]}."""
    index = {}
    shells = []
    for name in sorted(os.listdir(workspace)):
        shell_dir = os.path.join(workspace, name)
        if name.startswith(".") or not os.path.isdir(shell_dir):
            continue
        if os.path.realpath(shell_dir) == os.path.realpath(REPO_ROOT):
            continue  # this protocol checkout is not a shell
        sdks = load_shell_sdks(shell_dir)
        if sdks is None:
            continue
        shell = shell_repo_name(shell_dir)
        if shell in EXCLUDED_SHELLS:
            continue
        shells.append(shell)
        for entry in sdks:
            sdk = entry.get("name")
            if not sdk or not entry.get("enabled", True):
                continue
            repo = source_repo(entry)
            record = index.setdefault(sdk, {"repo": repo, "consumers": []})
            if repo and record["repo"] != repo:
                if not record["repo"]:
                    record["repo"] = repo
                else:
                    raise SystemExit(
                        f"[gen] {sdk}: conflicting source repos across shells "
                        f"({record['repo']} vs {repo} in {shell})"
                    )
            if shell not in record["consumers"]:
                record["consumers"].append(shell)
    for record in index.values():
        record["consumers"].sort()
    return index, shells


def sdk_halves(sdk_dir):
    """(dart, frappe, nextjs) presence for one SDK directory.

    dart/frappe are present when their manifest.json exists; nextjs is
    present when nextjs/ holds real content — any file beyond a
    `.gitignore` placeholder.
    """
    dart = os.path.isfile(os.path.join(sdk_dir, "dart", "manifest.json"))
    frappe = os.path.isfile(os.path.join(sdk_dir, "frappe", "manifest.json"))
    nextjs = False
    nextjs_dir = os.path.join(sdk_dir, "nextjs")
    if os.path.isdir(nextjs_dir):
        for _root, _dirs, files in os.walk(nextjs_dir):
            if any(name != ".gitignore" for name in files):
                nextjs = True
                break
    return dart, frappe, nextjs


def sha256_lf(data):
    """SHA-256 with CRLF folded to LF: the normalisation the Next.js
    composer's enforce_sdk_pin() and every shell's scripts/compose.sh apply,
    so this pin verifies against a checkout on a core.autocrlf machine."""
    return hashlib.sha256(data.replace(b"\r\n", b"\n")).hexdigest()


def nextjs_details(sdk_dir, sdk):
    """{"path", "version", "install_py_sha256"} for the SDK's Next.js half
    in a workspace checkout, or None when nextjs/ holds nothing beyond a
    .gitignore placeholder. version is manifest.json's, null when there is
    no manifest yet; install_py_sha256 is null when there is no install.py."""
    if not sdk_halves(sdk_dir)[2]:
        return None
    nextjs_dir = os.path.join(sdk_dir, "nextjs")
    version = None
    manifest = os.path.join(nextjs_dir, "manifest.json")
    if os.path.isfile(manifest):
        try:
            with open(manifest, "r", encoding="utf-8-sig") as handle:
                version = json.load(handle).get("version")
        except (OSError, ValueError):
            version = None
    pin = None
    installer = os.path.join(nextjs_dir, "install.py")
    if os.path.isfile(installer):
        with open(installer, "rb") as handle:
            pin = sha256_lf(handle.read())
    return {"path": f"{sdk}/nextjs", "version": version, "install_py_sha256": pin}


def repo_slug(repo_dir, name):
    """owner/repo of a workspace checkout from its git origin, else
    RokctAI/<dir name> (every censused monorepo lives under RokctAI)."""
    result = subprocess.run(
        ["git", "-C", repo_dir, "config", "--get", "remote.origin.url"],
        capture_output=True,
        text=True,
        check=False,
    )
    url = result.stdout.strip().rstrip("/").removesuffix(".git")
    parts = url.split("/")
    if result.returncode == 0 and len(parts) >= 2 and parts[-2] and parts[-1]:
        owner = parts[-2].split(":")[-1]  # git@github.com:Owner/repo
        return f"{owner}/{parts[-1]}"
    return f"RokctAI/{name}"


def scan_nextjs_halves(workspace):
    """Map sdk name (with the _sdk suffix) -> {"repo": owner/repo, "nextjs":
    details} for every SDK directory in the workspace's monorepos whose
    nextjs/ half has content. Same monorepo discovery as scan_census."""
    halves = {}
    for name in sorted(os.listdir(workspace)):
        repo_dir = os.path.join(workspace, name)
        if name.startswith(".") or not os.path.isdir(repo_dir):
            continue
        if os.path.realpath(repo_dir) == os.path.realpath(REPO_ROOT):
            continue
        if load_shell_sdks(repo_dir) is not None:
            continue
        repo = shell_repo_name(repo_dir)
        if repo in EXCLUDED_SHELLS or repo in ("SDKs", "BetAssist"):
            continue  # retired monorepos: a duplicate copy is never the source
        slug = repo_slug(repo_dir, repo)
        for sdk in sorted(os.listdir(repo_dir)):
            sdk_dir = os.path.join(repo_dir, sdk)
            if sdk.startswith(".") or not os.path.isdir(sdk_dir):
                continue
            details = nextjs_details(sdk_dir, sdk)
            if details is None:
                continue
            key = f"{sdk}_sdk"
            if key in halves:
                continue  # first monorepo in workspace order wins
            halves[key] = {"repo": slug, "nextjs": details}
    return halves


def github_raw(repo, path, token):
    """Bytes of <path> on <repo>'s default branch via the contents API, or
    None on 404. Used only by --nextjs-from-github."""
    request = urllib.request.Request(
        f"https://api.github.com/repos/{repo}/contents/{path}",
        headers={
            "Accept": "application/vnd.github.raw+json",
            "User-Agent": "rokct-protocol-gen-sdk-consumers",
            **({"Authorization": f"Bearer {token}"} if token else {}),
        },
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return response.read()
    except urllib.error.HTTPError as error:
        if error.code == 404:
            return None
        raise


def load_existing_index():
    path = os.path.join(REPO_ROOT, JSON_NAME)
    with open(path, "r", encoding="utf-8-sig") as handle:
        return json.load(handle).get("sdks") or {}


def census_nextjs_sdks():
    """{sdk_sdk: owner/repo} for every SDK the SDK_ECOSYSTEM.md census marks
    with a nextjs half, first repo in CENSUS_REPO_ORDER winning."""
    path = os.path.join(REPO_ROOT, ECOSYSTEM_NAME)
    with open(path, "r", encoding="utf-8") as handle:
        content = handle.read()
    start, end = content.find(CENSUS_START), content.find(CENSUS_END)
    found = {}
    if start < 0 or end < 0:
        return found
    for line in content[start:end].splitlines():
        cells = [c.strip().strip("`") for c in line.strip().strip("|").split("|")]
        if len(cells) < 5 or cells[0] in ("SDK", "") or set(cells[0]) <= set("-"):
            continue
        sdk, repo, nextjs = cells[0], cells[1], cells[4]
        if nextjs.lower() != "yes" or repo in ("SDKs", "BetAssist"):
            continue
        key = f"{sdk}_sdk"
        if key not in found or census_repo_key(repo) < census_repo_key(
            found[key].split("/")[-1]
        ):
            found[key] = f"RokctAI/{repo}"
    return found


def template_nextjs_sdks():
    """{sdk_sdk: owner/repo} for every git entry in a product template's
    sdks[] (core/utils/frappe/composer/*.json): an SDK a template already
    composes has a Next.js half even before the weekly census lists it."""
    found = {}
    templates_dir = os.path.join(REPO_ROOT, "core", "utils", "frappe", "composer")
    if not os.path.isdir(templates_dir):
        return found
    for name in sorted(os.listdir(templates_dir)):
        if not name.endswith(".json"):
            continue
        try:
            with open(
                os.path.join(templates_dir, name), "r", encoding="utf-8-sig"
            ) as handle:
                entries = json.load(handle).get("sdks") or []
        except (OSError, ValueError):
            continue
        for entry in entries:
            if isinstance(entry, dict) and entry.get("name") and source_repo(entry):
                found.setdefault(entry["name"], source_repo(entry))
    return found


def nextjs_halves_from_github(index, token):
    """The --nextjs-from-github counterpart of scan_nextjs_halves(): for
    every SDK already in the index plus every SDK the census marks with a
    nextjs half, read <sdk>/nextjs/manifest.json and install.py from the
    source repo's default branch. Returns the same shape."""
    candidates = {
        sdk: record["repo"] for sdk, record in index.items() if record.get("repo")
    }
    for sdk, repo in census_nextjs_sdks().items():
        candidates.setdefault(sdk, repo)
    for sdk, repo in template_nextjs_sdks().items():
        candidates.setdefault(sdk, repo)
    halves = {}
    for sdk in sorted(candidates):
        repo = candidates[sdk]
        short = sdk[:-4] if sdk.endswith("_sdk") else sdk
        manifest = github_raw(repo, f"{short}/nextjs/manifest.json", token)
        installer = github_raw(repo, f"{short}/nextjs/install.py", token)
        if manifest is None and installer is None:
            continue
        version = None
        if manifest is not None:
            try:
                version = json.loads(manifest.decode("utf-8-sig")).get("version")
            except ValueError:
                version = None
        halves[sdk] = {
            "repo": repo,
            "nextjs": {
                "path": f"{short}/nextjs",
                "version": version,
                "install_py_sha256": sha256_lf(installer)
                if installer is not None
                else None,
            },
        }
        print(
            f"[gen] {sdk:<18} {repo:<22} nextjs {version or '?':<8} "
            f"{(halves[sdk]['nextjs']['install_py_sha256'] or '-')[:12]}"
        )
    return halves


def merge_nextjs(index, halves):
    """Attach a `nextjs` block (or null) to every index record and add the
    SDKs that have a Next.js half but no consumer yet."""
    for sdk, record in index.items():
        half = halves.get(sdk)
        record["nextjs"] = half["nextjs"] if half else None
    for sdk, half in halves.items():
        if sdk not in index:
            index[sdk] = {
                "repo": half["repo"],
                "consumers": [],
                "nextjs": half["nextjs"],
            }
    return index


def scan_census(workspace):
    """Map repo -> [(sdk, dart, frappe, nextjs), ...] for SDK monorepos.

    An SDK monorepo is any sibling repo that is not an app shell (no root
    composer.json `sdks` list) but has at least one top-level directory
    with dart/manifest.json or frappe/manifest.json. Shells, `paas_pos`,
    and this protocol checkout are never censused.
    """
    census = {}
    for name in sorted(os.listdir(workspace)):
        repo_dir = os.path.join(workspace, name)
        if name.startswith(".") or not os.path.isdir(repo_dir):
            continue
        if os.path.realpath(repo_dir) == os.path.realpath(REPO_ROOT):
            continue  # this protocol checkout is not an SDK monorepo
        if load_shell_sdks(repo_dir) is not None:
            continue  # app shells are consumers, not SDK sources
        repo = shell_repo_name(repo_dir)
        if repo in EXCLUDED_SHELLS or repo in census:
            continue
        rows = []
        for sdk in sorted(os.listdir(repo_dir)):
            sdk_dir = os.path.join(repo_dir, sdk)
            if sdk.startswith(".") or not os.path.isdir(sdk_dir):
                continue
            dart, frappe, nextjs = sdk_halves(sdk_dir)
            if dart or frappe:
                rows.append((sdk, dart, frappe, nextjs))
        if rows:
            census[repo] = rows
    return census


def census_repo_key(repo):
    """Sort key keeping the doc's repo order, new repos after, by name."""
    if repo in CENSUS_REPO_ORDER:
        return (0, CENSUS_REPO_ORDER.index(repo), repo)
    return (1, 0, repo.lower())


def render_census(census):
    """The census markdown table (header + one row per SDK)."""
    lines = [
        "| SDK | Repo | dart | frappe | nextjs |\n",
        "|---|---|---|---|---|\n",
    ]
    for repo in sorted(census, key=census_repo_key):
        for sdk, dart, frappe, nextjs in census[repo]:
            halves = " | ".join(
                "yes" if half else "—" for half in (dart, frappe, nextjs)
            )
            lines.append(f"| `{sdk}` | `{repo}` | {halves} |\n")
    return "".join(lines)


def write_census(census):
    """Rewrite only the marked census block of SDK_ECOSYSTEM.md."""
    path = os.path.join(REPO_ROOT, ECOSYSTEM_NAME)
    with open(path, "r", encoding="utf-8") as handle:
        content = handle.read()
    start = content.find(CENSUS_START)
    end = content.find(CENSUS_END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit(
            f"[gen] {ECOSYSTEM_NAME}: census markers not found "
            f"({CENSUS_START} ... {CENSUS_END})"
        )
    block = f"{CENSUS_START}\n{render_census(census)}{CENSUS_END}"
    new_content = content[:start] + block + content[end + len(CENSUS_END) :]
    if new_content != content:
        with open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(new_content)
    return path


def write_json(index):
    payload = {
        "generated_by": "tools/gen_sdk_consumers.py",
        "sdks": {sdk: index[sdk] for sdk in sorted(index)},
    }
    json_path = os.path.join(REPO_ROOT, JSON_NAME)
    with open(json_path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")
    return json_path


def write_markdown(index):
    lines = [MARKDOWN_HEADER]
    for sdk in sorted(index):
        record = index[sdk]
        consumers = ", ".join(f"`{c}`" for c in record["consumers"]) or "—"
        half = record.get("nextjs") or {}
        path = f"`{half['path']}`" if half.get("path") else "—"
        version = f"`{half['version']}`" if half.get("version") else "—"
        pin = f"`{half['install_py_sha256']}`" if half.get("install_py_sha256") else "—"
        lines.append(
            f"| `{sdk}` | `{record['repo']}` | {path} | {version} | {pin} | {consumers} |\n"
        )
    md_path = os.path.join(REPO_ROOT, MARKDOWN_NAME)
    with open(md_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("".join(lines))
    return md_path


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--workspace",
        default=os.path.dirname(REPO_ROOT),
        help="Multi-repo workspace to scan; default is the parent directory "
        "of this protocol checkout.",
    )
    parser.add_argument(
        "--nextjs-from-github",
        action="store_true",
        help="Keep the committed index's consumers and refresh only each "
        "SDK's Next.js path/version/pin from the source repos' default "
        "branches over the GitHub API (GH_TOKEN for private repos). For a "
        "maintainer without a workspace; the weekly refresh scans its "
        "workspace instead.",
    )
    args = parser.parse_args(argv)

    if args.nextjs_from_github:
        index = load_existing_index()
        if not index:
            raise SystemExit(f"[gen] {JSON_NAME} carries no index to refresh")
        halves = nextjs_halves_from_github(index, os.environ.get("GH_TOKEN"))
        merge_nextjs(index, halves)
        shells = sorted({c for record in index.values() for c in record["consumers"]})
        workspace = "(GitHub API, --nextjs-from-github)"
    else:
        workspace = os.path.abspath(args.workspace)
        if not os.path.isdir(workspace):
            raise SystemExit(f"[gen] Workspace not found: {workspace}")

        index, shells = scan_workspace(workspace)
        if not shells:
            raise SystemExit(
                f"[gen] No app shells (root composer.json with an `sdks` list) "
                f"found under {workspace}"
            )
        merge_nextjs(index, scan_nextjs_halves(workspace))

    json_path = write_json(index)
    md_path = write_markdown(index)

    print(f"[gen] Scanned workspace {workspace}")
    print(f"[gen] Found {len(shells)} app shell(s): {', '.join(sorted(shells))}")
    print(f"[gen] Wrote {os.path.relpath(json_path, REPO_ROOT)} ({len(index)} SDKs)")
    print(f"[gen] Wrote {os.path.relpath(md_path, REPO_ROOT)}")

    if args.nextjs_from_github:
        print(
            f"[gen] --nextjs-from-github: {ECOSYSTEM_NAME} census block left as committed"
        )
        return 0

    census = scan_census(workspace)
    if census:
        census_path = write_census(census)
        total = sum(len(rows) for rows in census.values())
        print(
            f"[gen] Wrote census block in {os.path.relpath(census_path, REPO_ROOT)} "
            f"({total} SDKs across {len(census)} repos)"
        )
    else:
        print(
            f"[gen] WARNING: no SDK monorepos found under {workspace}; "
            f"left the {ECOSYSTEM_NAME} census block untouched"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
