#!/usr/bin/env python3
# Copyright (c) 2026 RokctAI
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Licensed under the MIT License.
# Copyright 2024 RokctAI
"""Generate the SDK -> consuming-app-shells reverse index.

An app shell is a repository whose ROOT composer.json declares an `sdks`
list (the composed-shell contract, see SDK_ECOSYSTEM.md "App composition").
Each entry names an SDK and the source repository it is composed from. This
tool inverts that relationship across a multi-repo workspace so that anyone
changing an SDK can see every shell that composes it:

  python3 tools/gen_sdk_consumers.py

1. scans every sibling directory of this protocol checkout (override with
   --workspace DIR) for a root composer.json containing an `sdks` list,
2. records, per enabled SDK entry, its source repo (owner/repo from the
   entry's `git` URL) and the shell repos that compose it, and
3. writes both outputs at the repo root: sdk_consumers.json (machine
   readable, consumed by shared-workflows/scripts/sdk_validator.py) and
   SDK_CONSUMERS.md (the human-readable table).

Output is deterministic: sorted keys, LF line endings, trailing newline, no
timestamps — regenerating against an unchanged workspace produces zero diff.
Entries with `"enabled": false` are not composed into the shell and are
therefore not indexed. `paas_pos` is not indexed (owner rule).
"""

import argparse
import json
import os
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_NAME = "sdk_consumers.json"
MARKDOWN_NAME = "SDK_CONSUMERS.md"

# Shell repos deliberately left out of the index. One-line note only.
EXCLUDED_SHELLS = {"paas_pos"}  # not indexed (owner rule)

MARKDOWN_HEADER = """# SDK consumers

Reverse index: for every SDK, the app shells that compose it. An app shell
is a repo whose root `composer.json` declares an `sdks` list (see
SDK_ECOSYSTEM.md, "App composition"); this table inverts those lists so a
change to an SDK can be checked against every shell that ships it — a
breaking SDK change must land together with fixes for all of its consumers
(backward-compatibility invariant, SDK_ECOSYSTEM.md).

Generated by `tools/gen_sdk_consumers.py` from a multi-repo workspace
checkout — do not edit by hand. Regenerate with:

```sh
python3 tools/gen_sdk_consumers.py
```

Disabled entries (`"enabled": false`) are not composed and not indexed.
`paas_pos` is not indexed.

| SDK | Source repo | Consuming shells |
|---|---|---|
"""


def shell_repo_name(shell_dir):
    """The shell's repo name — from its git origin URL, else the dir name.

    Every shell's composer.json carries the same manifest name
    ("rokctapp_composer"), so the repository identity comes from the clone
    itself. The directory name is the fallback for non-git checkouts.
    """
    result = subprocess.run(
        ["git", "-C", shell_dir, "config", "--get", "remote.origin.url"],
        capture_output=True,
        text=True,
        check=False,
    )
    url = result.stdout.strip()
    if result.returncode == 0 and url:
        return url.rstrip("/").removesuffix(".git").rsplit("/", 1)[-1]
    return os.path.basename(os.path.normpath(shell_dir))


def source_repo(entry):
    """owner/repo from an sdks[] entry's `git` URL (e.g. RokctAI/core)."""
    url = (entry.get("git") or "").rstrip("/").removesuffix(".git")
    parts = url.split("/")
    if len(parts) >= 2 and parts[-2] and parts[-1]:
        return f"{parts[-2]}/{parts[-1]}"
    return ""


def load_shell_sdks(shell_dir):
    """The parsed `sdks` list of shell_dir's root composer.json, or None."""
    composer_path = os.path.join(shell_dir, "composer.json")
    if not os.path.isfile(composer_path):
        return None
    try:
        with open(composer_path, "r", encoding="utf-8-sig") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return None
    sdks = data.get("sdks")
    if not isinstance(sdks, list):
        return None
    return sdks


def scan_workspace(workspace):
    """Map sdk name -> {"repo": owner/repo, "consumers": [shell, ...]}."""
    index = {}
    shells = []
    for name in sorted(os.listdir(workspace)):
        shell_dir = os.path.join(workspace, name)
        if name.startswith(".") or not os.path.isdir(shell_dir):
            continue
        if os.path.realpath(shell_dir) == os.path.realpath(REPO_ROOT):
            continue  # this protocol checkout is not a shell
        sdks = load_shell_sdks(shell_dir)
        if sdks is None:
            continue
        shell = shell_repo_name(shell_dir)
        if shell in EXCLUDED_SHELLS:
            continue
        shells.append(shell)
        for entry in sdks:
            sdk = entry.get("name")
            if not sdk or not entry.get("enabled", True):
                continue
            repo = source_repo(entry)
            record = index.setdefault(sdk, {"repo": repo, "consumers": []})
            if repo and record["repo"] != repo:
                if not record["repo"]:
                    record["repo"] = repo
                else:
                    raise SystemExit(
                        f"[gen] {sdk}: conflicting source repos across shells "
                        f"({record['repo']} vs {repo} in {shell})"
                    )
            if shell not in record["consumers"]:
                record["consumers"].append(shell)
    for record in index.values():
        record["consumers"].sort()
    return index, shells


def write_json(index):
    payload = {
        "generated_by": "tools/gen_sdk_consumers.py",
        "sdks": {sdk: index[sdk] for sdk in sorted(index)},
    }
    json_path = os.path.join(REPO_ROOT, JSON_NAME)
    with open(json_path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")
    return json_path


def write_markdown(index):
    lines = [MARKDOWN_HEADER]
    for sdk in sorted(index):
        record = index[sdk]
        consumers = ", ".join(f"`{c}`" for c in record["consumers"])
        lines.append(f"| `{sdk}` | `{record['repo']}` | {consumers} |\n")
    md_path = os.path.join(REPO_ROOT, MARKDOWN_NAME)
    with open(md_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("".join(lines))
    return md_path


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--workspace",
        default=os.path.dirname(REPO_ROOT),
        help="Multi-repo workspace to scan; default is the parent directory "
        "of this protocol checkout.",
    )
    args = parser.parse_args(argv)

    workspace = os.path.abspath(args.workspace)
    if not os.path.isdir(workspace):
        raise SystemExit(f"[gen] Workspace not found: {workspace}")

    index, shells = scan_workspace(workspace)
    if not shells:
        raise SystemExit(
            f"[gen] No app shells (root composer.json with an `sdks` list) "
            f"found under {workspace}"
        )

    json_path = write_json(index)
    md_path = write_markdown(index)

    print(f"[gen] Scanned workspace {workspace}")
    print(f"[gen] Found {len(shells)} app shell(s): {', '.join(sorted(shells))}")
    print(f"[gen] Wrote {os.path.relpath(json_path, REPO_ROOT)} ({len(index)} SDKs)")
    print(f"[gen] Wrote {os.path.relpath(md_path, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
