name: Auto Assign
on:
  pull_request:
    types: [opened]

jobs:
  assign:
    uses: RokctAI/shared-workflows/.github/workflows/universal-assign.yml@e6e29abcfeb0282f0be44ab21fb16d4f92957e6e # shared-workflows main @ 2026-08-15
    permissions: write-all
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
