name: Auto Label
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    uses: RokctAI/shared-workflows/.github/workflows/universal-labeler.yml@3ad81fe42b9302f6601510bb8902aab8fa7613e7 # shared-workflows main @ 2026-08-22
    permissions: write-all
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
