name: Auto Label
on:
  issues:
    types: [opened, edited]

jobs:
  label:
    uses: RokctAI/shared-workflows/.github/workflows/universal-labeler.yml@09494edd4824cc6fca95ea96a2db4d238c4561b3 # shared-workflows main @ 2026-08-26
    permissions: write-all
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
