name: License Eye
on:
  pull_request:

jobs:
  license:
    uses: RokctAI/shared-workflows/.github/workflows/universal-license.yml@2c7f49674dc9c14ca390f3342ad514cff59f64f5 # shared-workflows main @ 2026-08-21
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
