name: License Eye
on:
  pull_request:

jobs:
  license:
    uses: RokctAI/shared-workflows/.github/workflows/universal-license.yml@97d7d6f3a7ed312da4c651be55ea95774c190a89 # shared-workflows main @ 2026-08-16
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
