name: Link Checker
on:
  schedule:
    - cron: '30 2 * * 0' # Weekly on Sunday
  workflow_dispatch:

jobs:
  links:
    uses: RokctAI/shared-workflows/.github/workflows/universal-links.yml@e6e29abcfeb0282f0be44ab21fb16d4f92957e6e # shared-workflows main @ 2026-08-15
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
