name: Link Checker
on:
  schedule:
    - cron: '30 2 * * 0' # Weekly on Sunday
  workflow_dispatch:

jobs:
  links:
    uses: RokctAI/shared-workflows/.github/workflows/universal-links.yml@dd18f9dee1976728aea6156fc6efbf2951d1bc75 # shared-workflows main @ 2026-08-22
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
