name: Link Checker
on:
  schedule:
    - cron: '30 2 * * 0' # Weekly on Sunday
  workflow_dispatch:

jobs:
  links:
    uses: RokctAI/shared-workflows/.github/workflows/universal-links.yml@3ad81fe42b9302f6601510bb8902aab8fa7613e7 # shared-workflows main @ 2026-08-22
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
