name: Auto Merge

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge:
    uses: RokctAI/shared-workflows/.github/workflows/universal-merge.yml@dd18f9dee1976728aea6156fc6efbf2951d1bc75 # shared-workflows main @ 2026-08-22
    permissions: write-all
    with:
      allowed_users: 'RendaniSinyage, Rendani Sinyage, rokctbot, rokctbot[bot]'
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
