name: Security Scan
on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    permissions: write-all
    uses: RokctAI/shared-workflows/.github/workflows/universal-security.yml@2c7f49674dc9c14ca390f3342ad514cff59f64f5 # shared-workflows main @ 2026-08-21
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      MONOREPO_PAT: ${{ secrets.MONOREPO_PAT }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

