name: Security Scan
on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    permissions: write-all
    uses: RokctAI/shared-workflows/.github/workflows/universal-security.yml@1d5ebbcdf3dc771fed587fe90e5f91f3a305392c # shared-workflows main @ 2026-08-24
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      MONOREPO_PAT: ${{ secrets.MONOREPO_PAT }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

