name: Security Scan
on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    permissions: write-all
    uses: RokctAI/shared-workflows/.github/workflows/universal-security.yml@c9acb66a7449b7ecaef6c909fbf8b0f899464ac5 # shared-workflows main @ 2026-08-22
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
      MONOREPO_PAT: ${{ secrets.MONOREPO_PAT }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

