name: Semantic PR
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  semantic:
    uses: RokctAI/shared-workflows/.github/workflows/universal-semantic.yml@6c22598ecd6a654f40d83ebb704763da5190b9a0 # shared-workflows main @ 2026-08-20
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
