name: Semantic PR
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  semantic:
    uses: RokctAI/shared-workflows/.github/workflows/universal-semantic.yml@c9acb66a7449b7ecaef6c909fbf8b0f899464ac5 # shared-workflows main @ 2026-08-22
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
