name: Welcome Bot
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    uses: RokctAI/shared-workflows/.github/workflows/universal-welcome.yml@35c8f0677c1b2b3b73d3c6883bf102f192ca2bcd # shared-workflows main @ 2026-08-21
    permissions: write-all
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
