name: Welcome Bot
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    uses: RokctAI/shared-workflows/.github/workflows/universal-welcome.yml@09494edd4824cc6fca95ea96a2db4d238c4561b3 # shared-workflows main @ 2026-08-26
    permissions: write-all
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
