name: Welcome Bot
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  welcome:
    uses: RokctAI/shared-workflows/.github/workflows/universal-welcome.yml@dd18f9dee1976728aea6156fc6efbf2951d1bc75 # shared-workflows main @ 2026-08-22
    permissions: write-all
    secrets:
      COUNTER_API_KEY: ${{ secrets.COUNTER_API_KEY }}
